D-Answer/config/routes.rb
require 'role_model'
DAnswer::Application.routes.draw do  
  
  get "my_questions/index"

  get "questions/up"

  get "questions/down"

  get "answers/up"

  get "answers/down"

  get "answers/favorite"

  get "home/index"
  get 'tags/:tag', to: 'questions#index', as: :tag
  get 'tags/', to: 'tags#index'
  
  devise_for :users

  resources :users
  
  resources :questions do
    resources :comment_qs
    resources :answers do
      resource :comment_as 
    end
  end
    

  root :to => 'questions#index'

end

D-Answer/app/models/user.rb
require 'role_model'

class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :votequestions
  has_many :questions, :through => :votequestions

  has_many :voteanswers
  has_many :answers, :through => :voteanswers

  has_many :questions, :class_name => "Question"
  has_many :answers, :class_name => "Answer"
  has_many :commentqs, :class_name => "CommentQ"
  has_many :commentas, :class_name => "CommentA"
  
  has_attached_file :pic, :styles => { :small => "100x100>" },
                          :url  => "/assets/products/:id/:style/:basename.:extension",
                          :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"


  ROLES = %w[admin user]

  include RoleModel 
  roles :admin, :user
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :login, :name, :lastname, :bio, :rating, :role, :score, :pic
    
  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask
  
  #validates_numericality_of :rating
  VALID_STRING_REGEX = /\A[\w+\-\\!\?\,\.\"\' .]*\z/
  validates :login, presence: true, uniqueness: true, format: { with: VALID_STRING_REGEX }, :length => { :in => 1..15 }
  validates :name, format: { with: VALID_STRING_REGEX }
  validates :lastname, format: { with: VALID_STRING_REGEX }
  validates :password, format: { with: VALID_STRING_REGEX }
end

D-Answer/app/controllers/users_controller.rb
#encoding: UTF-8
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :create, :destroy, :show] 
  before_filter :is_authorize, :only => [:show, :edit, :update, :destroy]
  before_filter :is_admin, :only => [:index] #Solo admin puede listar usuarios

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @question = Question.where( :user_id => params[:id] )
    authorize! :read, @user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
      format.json { render json: @question }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    authorize! :create, @user

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    authorize! :update, @user

  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])
    @user.score = 0
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Usuario creado correctamente.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'Usuario actualizado.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    authorize! :destroy, @user
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

D-Answer/app/helpers/users_helper.rb
module UsersHelper
end

D-Answer/app/views/users/_form.html.erb
<%= semantic_form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <table style="width:700px;text-align:center">
    <tr>
      <td>
        <div><b><%= f.label :username %></b><br />
        <%= f.text_field :login, :autofocus => true %></div>
      </td>
      <td>
        <div><b><%= f.label :email %></b><br />
        <%= f.email_field :email %></div>
      </td>
    </tr>
    <tr>
      <td>
        <div><b><%= f.label :nombre %></b><br />
        <%= f.text_field :name %></div>
      </td>
      <td>
        <div><b><%= f.label :apellido %></b><br />
        <%= f.text_field :lastname %></div>
      </td>
    </tr>
     <tr>
      <td colspan="2" style="text-align: center;">
         <%= f.file_field :pic %>
      </td>
      <% if signed_in? %>
        <%= f.input :score, :as => :hidden %>
      <% else %>
          <%= f.input :score, :as => :hidden, :value => "0" %>
      <% end %>
    </tr>
  </table>
  
  <div class="actions", style="text-align: center;margin-top:20px;margin-right:250px">
    <%= f.submit "Actualizar Usuario"%>
  </div>  
<% end %>

D-Answer/app/views/users/edit.html.erb
<div style="width:800px;height:40px"> 
  <div class="title" style="float:left">
    Editar Usario
  </div>

  <div style="margin-left:10px;margin-top:15px;float:left">
    <%= link_to 'Volver', :back, :class => 'boton' %>
  </div>
</div>

<%= render 'form' %>

D-Answer/app/views/users/index.html.erb
<div class="title">Lista de Usuarios</div> 
<%= link_to 'Volver', questions_path, :class => 'boton' %>
<div style="float:right;margin-top:15px;margin-right:50px"><%= link_to 'Nuevo Admin', new_user_path, :class => 'boton' %></div>


<table class="list_users">
  <tr>
    <th>Login</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Email</th>
    <th>Permisos</th>
    <th>Score</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.login, user, :title => user.login  %></td>
    <td><%= user.name %></td>
    <td><%= user.lastname %></td>
    <td><%= user.email %></td>    
    <td><%= user.role %></td>
    <td><%= user.score %></td>
    <td><%= link_to '✎', edit_user_path(user) %></td>
    <td><%= link_to 'X', user, method: :delete, data: { confirm: 'Are you sure?' }, :style => 'color:red' %></td>
  </tr>
<% end %>
</table>

D-Answer/app/views/users/new.html.erb
<% if current_user && current_user.role == "admin" %>
  <div class="title">Crear Nuevo Admin</div> 
  <%= link_to 'Volver', users_path, :class => 'boton' %>
  <%= render 'form' %>
<% else %>
  <div style="width:100%;text-align:center;margin-top:30px">
    <h2> Debe ser admin para poder crear otros usuarios. </h2>
    <%= link_to 'Volver', questions_path, :class => 'boton' %>
  </div>
<% end %>

D-Answer/app/views/users/show.html.erb
<div style="margin-left:80px;height:40px ;">
  <div style="display:inline-block;border-bottom:1px solid #3b88c0;float:left">
    <b>Usuario:</b> 
    <div class="title" style="margin-left:10px;border-bottom:none">
      <%= @user.login %>
    </div>
  </div>
  <div style="margin-left:10px;margin-top:15px;float:left">
    <%= link_to 'Editar', edit_user_path(@user), :class => 'boton'%>
    <%= link_to 'Volver', users_path, :class => 'boton'%>
  </div>
</div>


<table id="show_user">
  <tr>
    <td colspan="2" rowspan="2">
      <%= image_tag @user.pic.url(:small) %>
    </td>
    <td>
      <b> Nombre: </b>  
      <%= @user.name %>
    </td>
    <td>
      <b> Apellido: </b>
      <%= @user.lastname %>
    </td>
  </tr>
  <tr>
    <td >
      <b> Email: </b>  
      <%= @user.email %>
    </td>
    <td>
      <b> Score: </b>
      <%= @user.score %>
    </td>
  </tr>
  </tr>
</table>

<% if current_user && current_user.role != "admin" %>  
  <div id="todas">
    <div class="title">Mis Preguntas</div>
    <%= link_to 'Nueva Pregunta', new_question_path, :class => 'boton', :style => "float:right;margin-top:15px;margin-right:50px"%>


      <table class="list_questions">

        <% if !@question.blank? %>
          <% @question.sort {|a,b| b.created_at <=> a.created_at }.each do |question| %>
          <tr>
              <td id="titulo">
                <%= link_to question.title, question, :title => question.title %>
              </td>
              
              <td>
                <%= question.created_at.day %>/<%= question.created_at.month %>/<%= question.created_at.year %>
                &nbsp  &nbsp
                <%= question.created_at.strftime("%I:%M%p") %>
              </td>
              
              <td id="last_row">
                <%= link_to 'X', question, method: :delete, data: { confirm: 'Are you sure?' }, :style=> 'color:red' %>
              </td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td>
            No has hecho ninguna pregunta.
            </td>
          </tr>
        <% end %>


      </table>
  </div>
<% end %>