D-Answer/config/routes.rb
require 'role_model'
DAnswer::Application.routes.draw do  
  
  get "my_questions/index"

  get "questions/up"

  get "questions/down"

  get "answers/up"

  get "answers/down"

  get "answers/favorite"

  get "home/index"
  get 'tags/:tag', to: 'questions#index', as: :tag
  get 'tags/', to: 'tags#index'
  
  devise_for :users

  resources :users
  
  resources :questions do
    resources :comment_qs
    resources :answers do
      resource :comment_as 
    end
  end
    

  root :to => 'questions#index'

end

D-Answer/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
end

D-Answer/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    render :nothing => true
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

D-Answer/app/helpers/tags_helper.rb
module TagsHelper
end

D-Answer/app/views/tags/_form.html.erb
<%= semantic_form_for @tag do |f| %>
  <%= f.inputs do %>
    <%= f.input :name %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

D-Answer/app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

D-Answer/app/views/tags/index.html.erb
<div class="title">Tags</div>

<table style="margin-top: 20px;width:1000px;text-align:center">
  <% if !@tags.blank? %>
    <% @tags.in_groups_of(10, false) do |row| %>
      <tr style="width:100px">
	<% for tag in row %>
	  <td><%= link_to tag.name, tag_path(tag.name) %></td>
	<% end %>
      </tr>
    <% end %>
  <% else %>
        <tr>
          <td>
            No hay etiquetas en la base de datos.
          </td>
        </tr>  
        <% end %>
    </table>
</table>

D-Answer/app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

D-Answer/app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>