D-Answer/config/routes.rb
require 'role_model'
DAnswer::Application.routes.draw do  
  
  get "my_questions/index"

  get "questions/up"

  get "questions/down"

  get "answers/up"

  get "answers/down"

  get "answers/favorite"

  get "home/index"
  get 'tags/:tag', to: 'questions#index', as: :tag
  get 'tags/', to: 'tags#index'
  
  devise_for :users

  resources :users
  
  resources :questions do
    resources :comment_qs
    resources :answers do
      resource :comment_as 
    end
  end
    

  root :to => 'questions#index'

end

D-Answer/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :votequestions
  has_many :users, :through => :votequestions

  belongs_to :user
  
  has_many :answers, :dependent => :destroy
  
  has_many :comment_qs, :dependent => :destroy
  
  accepts_nested_attributes_for :comment_qs, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  attr_accessible :title, :category, :content, :published_on, :created_at, :score, :tag_list
  
  acts_as_taggable
  

  VALID_STRING_REGEX = /\A[\w+\-\\!\?\,\.\"\' .]*\z/

  validates :title, presence: true, uniqueness: true, format: { with: VALID_STRING_REGEX }
  validates :content, presence: true, format: { with: VALID_STRING_REGEX }
  
  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

D-Answer/app/controllers/questions_controller.rb
#encoding: UTF-8
class QuestionsController < ApplicationController
before_filter :authenticate_user!, :only => [:new, :create, :destroy]
before_filter :is_owner, :only => [:edit]
  # GET /questions
  # GET /questions.json
  def index
    if params[:tag]
      @questions = Question.tagged_with(params[:tag])
    else
      @questions = Question.search(params[:search])
    end

    respond_to do |format|
      format.html # my_questions.html.erb
      format.json { render json: @questions }
    end
  end

  def up
    @question = Question.find(params[:id])
    v = Votequestion.where(:question_id => @question.id, :user_id => current_user)    

    if v.length > 0
      nuevo = v[0]
      case nuevo.vote.to_i
      when -1
        valor = 0
      when 0
        valor = 1
      when 1
        redirect_to question_path(@question.id), notice: 'Solo puede votar 1 vez.'
        return
      end
    else
      nuevo = Votequestion.new(:user_id => current_user.id, :question_id => @question.id, :vote => 1)
      valor = 1
      if not nuevo.save
        redirect_to question_path(@question.id), notice: 'Error intente más tarde.'
      end
    end

    user = User.find(@question.user_id)
    score = @question.score + 1
    uscore = user.score + 1
    if @question.update_attribute('score', score) and user.update_attribute('score', uscore) and nuevo.update_attribute('vote',valor)
      
      redirect_to @question, notice: 'Voto actualizado.'
    else
      redirect_to @question, notice: 'Error intente más tarde.'
    end
  end


  def down
    @question = Question.find(params[:id])
    v = Votequestion.where(:question_id => @question.id, :user_id => current_user)

    if v.length > 0
      nuevo = v[0]
      case nuevo.vote.to_i
      when 1
        valor = 0
      when 0
        valor = -1
      when -1
        redirect_to question_path(@question.id), notice: 'Sólo puede votar 1 vez.'
        return
      end
    else
      nuevo = Votequestion.new(:user_id => current_user.id, :question_id => @question.id, :vote => -1)
      valor = -1
      if not nuevo.save
        redirect_to question_path(@question.id), notice: 'Error intente más tarde.'
      end
    end

    user = User.find(@question.user_id)
    score = @question.score - 1
    uscore = user.score - 1
    if @question.update_attribute('score', score) and user.update_attribute('score', uscore) and nuevo.update_attribute('vote',valor)      
      redirect_to @question, notice: 'Voto actualizado.'
    else
      redirect_to @question, notice: 'Error intente más tarde.'
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
    #authorize! :read, @question

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new
    authorize! :create, @question

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
    authorize! :update, @question
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    @question.score = 0
    
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Pregunta creada correctamente.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Pregunta editada correctamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    authorize! :destroy, @question
    @question.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

D-Answer/app/helpers/questions_helper.rb
module QuestionsHelper
end

D-Answer/app/views/questions/_form.html.erb
<%= semantic_form_for @question do |f| %>
  <table class="create_question">
  <%= hidden_field_tag :direction, params[:direction] %>
  <%= hidden_field_tag :sort, params[:sort] %>
    <tr>
      <td>
        <spam style="margin-left:10px">
          <b> TÍTULO </b>
        </spam>
        <%= f.input :title, :label => false, :input_html => { :size => 60 } %>
      </td>
    </tr>  

    <tr>
      <td>
        <spam style="margin-left:10px">
          <b> CATEGORÍAS (separadas por coma)</b>
        </spam>
        <%= f.input :tag_list, :label => false, :input_html => { :size => 60 } %>
      <td>
    </tr>  

    <tr>
      <td>
        <spam style="margin-left:10px">
          <b> CONTENIDO </b>
        </spam>
        <%= f.input :content, :as => :text, :label => false, :input_html => { :rows => 20, :cols => 120 } %>
      </td>
     <tr>
      <td>        
        <%= f.input :score, :as => :hidden, :value => "0" %></div>
      </td>
    </tr>
  </table>
  
  <div class="actions", style="text-align: right;margin-top:20px;margin-right:75px">
    <%= f.submit "Actualizar Pregunta"%>
  </div>  
<% end %>

D-Answer/app/views/questions/_question_table.html.erb
<div id="todas">
  <div class="title">Preguntas</div>
  <% if user_signed_in? %>
    <%= link_to 'Nueva Pregunta', new_question_path, :class => 'boton', :style => "float:right;margin-top:15px;margin-right:50px"%>
  <% end %>

  <%= form_tag questions_path, :method => 'get', :id => "questions_search" do %>
    <div style="float:right;margin-right:50px;margin-top:10px;margin-bottom: 20px;">    
      <%= text_field_tag :search, params[:search], :placeholder => "Buscar", :size => 30 %>
      <%= submit_tag "Buscar", :name => nil %>
    </div>

    <table class="list_questions">

      <% if !@questions.blank? %>
        <% @questions.sort {|a,b| b.created_at <=> a.created_at }.each do |question| %>
        <tr>
            <td id="titulo">
              <%= link_to question.title, question, :title => question.title %>
            </td>
            
            <td>
              <%= question.created_at.day %>/<%= question.created_at.month %>/<%= question.created_at.year %>
              &nbsp  &nbsp
              <%= question.created_at.strftime("%I:%M%p") %>
            </td>
            
            <% if current_user && current_user.role == "admin" %>  
              <td id="last_row">
                <%= link_to 'X', question, method: :delete, data: { confirm: 'Are you sure?' }, :style=> 'color:red' %>
              </td>
              <% end %>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td>
            No hay preguntas en la base de datos.
          </td>
        </tr>  
        <% end %>
    </table>
  <% end %>
</div>

D-Answer/app/views/questions/edit.html.erb
<div style="width:800px !important;height:40px !important"> 
  <div class="title" style="float:left">
    Editar Pregunta
  </div>

  <div style="margin-left:10px;margin-top:15px;float:left">
    <%= link_to 'Volver', :back, :class => 'boton' %>
  </div>
</div>

<%= render 'form' %>

D-Answer/app/views/questions/index.html.erb
<script>
   function show(target){
        document.getElementById(target).style.display = 'block';
    }

    function hide(target){
        document.getElementById(target).style.display = 'none';
    }

    function mispreguntas() {
      $('a[data-confirm], a[data-method], a[data-remote]').live('click.rails', function(e) {
        var link = $(this);
        if (!allowAction(link)) return false;

        if (link.attr('data-remote')) {
          handleRemote(link);
          return false;
        } else if (link.attr('data-method')) {
          handleMethod(link);
          return false;
        }   
      });
    }
</script>

<%= render 'question_table' %>

D-Answer/app/views/questions/new.html.erb
<div>
  <div class="title" style="float:left">
    Nueva Pregunta
  </div>
  <div style="margin-left:10px;margin-top:15px;float:left">
    <%= link_to 'Volver', :back, :class => 'boton' %>
  </div>
</div>

<%= render 'form' %>

D-Answer/app/views/questions/show.html.erb
<div>
  <div style="border-bottom:1px solid #2a638f">
    <div class="title" style="border-bottom:none"> <%= @question.title %> </div>
    <div style="float:right;margin-top:10px;margin-right:30px;">
      <% if current_user == User.find(@question.user_id) %>
        <%= link_to 'Editar', edit_question_path(@question), :class => 'boton' %>
      <% end %>
      <%= link_to 'Volver', questions_path, :class => 'boton' %>
    </div>
  </div>
  
  <div class="question_info">
      <div>
        <b>Fecha creación:</b>
        <%= @question.created_at.day %>/<%= @question.created_at.month %>/<%= @question.created_at.year %>
        <%= @question.created_at.strftime("%I:%M%p") %>
      </div>
      <div>
        <b>Autor:</b> <%= User.find(@question.user_id).login %>
      </div>
  </div>
  
  <table id="table_question">
    <tr>
      <td>
        <b>Score:</b> 
      </td>
      <td>
        <%= @question.score %>
          <%= link_to '⬆', questions_up_path(:id => @question), :style => 'color:green' %>          
          <%= link_to '⬇', questions_down_path(:id => @question), :style => 'color:red' %>
        
      </td>
    </tr>
    <tr>
      <td>
        <b> Tags: </b>
      </td>
      <td>  
        <%= raw @question.tag_list.map { |t| link_to t, tag_path(t)}.join(', ') %>
      </td>
    </tr>
    <tr>
      <td style="vertical-align: top;">
        <b> Pregunta: </b>
      </td>
      <td style="text-align:justify;">  
        <%= @question.content %>
      </td>
    </tr>
  </table>

  <div>
    <div style="font-size:small;margin-left:120px;border-top:5px double #999">
      
      <h3 style="margin-left: 20px;"> <%= @question.comment_qs.size %> Comentario(s) </h3>
      
      <% @question.comment_qs.each do |c| %>
        <% if c.content %>
          <li style="list-style:none;border-top:1px solid #999">
            <p>
              <div style="font-style:italic">
                <b>Autor:</b> <%= User.find(c.user_id).login %>
                <b> | Fecha: </b>
                <%= c.created_at.day %>/<%= c.created_at.month %>/<%= c.created_at.year %>
                <%= c.created_at.strftime("%I:%M%p") %>
                <spam style="float:right;font-style:normal">
                </spam>
              </div>
              <div style="margin:20px 20px">
                <%= c.content %>
              </div>
            </p>
          </li>
        <% end %>
      <% end %>

      <% if user_signed_in? && current_user.role =="user" %>
	<div style="padding-top:20px;border-top:4px dotted #999;margin-left:20px;margin-right: 353px;">
	  <spam style="margin-left:20px;font-style:italic"><b> Deja tu comentario </b></spam>
	  <%= form_for [@question, @question.comment_qs.build] do |f| %>
	    <div class="field">
	      <%= f.text_area :content, :cols => 70, :rows => 3, :placeholder => "Agrega un comentario." %>
	    </div>
	    <div class="actions">
	      <%= f.submit "Comentar"%>
	    </div>
	  <% end %>
	</div>
      <% end %>
    </div>
  </div>

<div style="border-top: 10px double #2a638f;margin-top: 20px;">
  <% @question.answers.where( :fav => 1 ).each do |fav| %>
      <% if fav.content %>
        <li style="list-style:none">
          <p>
            <div style="font-style:italic">
              <div style="text-align: center;background-color: green;color:white;margin-bottom: 5px;"> 
                ★ Respuesta aceptada por el usuario ★ 
              </div>
              <b>Autor:</b> <%= User.find(fav.user_id).login %>
              <b> | Fecha: </b>
              <%= fav.created_at.day %>/<%= fav.created_at.month %>/<%= fav.created_at.year %>
              <%= fav.created_at.strftime("%I:%M%p") %>

              <spam style="float:right;font-style:normal">
                <% if current_user == User.find(@question.user_id) %> 
                  <%= link_to '★', answers_favorite_path(:id => @question, :answer => fav), :style => 'color:green' %>
                <% end %>
                <b>Score: </b><%= fav.score %>
                <%= link_to '⬆', answers_up_path(:id => @question, :answer => fav), :style => 'color:green' %>          
                <%= link_to '⬇', answers_down_path(:id => @question, :answer => fav), :style => 'color:red' %>
                <%= link_to 'Comentar', new_question_answer_comment_as_path(@question, fav), :class => 'boton' %>
              </spam>
            </div>
            <div style="margin:20px 20px">
              <%= fav.content %>
              <% fav.comment_as.each do |t| %>
                <% if t.content %>
                  <div style="font-size:small;margin-left:120px;border-top:5px double #999">
                    <p>
                      <div style="font-style:italic">
                        <b>Autor:</b> <%= User.find(t.user_id).login %>
                        <b> | Fecha: </b>
                        <%= t.created_at.day %>/<%= t.created_at.month %>/<%= t.created_at.year %>
                        <%= t.created_at.strftime("%I:%M%p") %>
                        <spam style="float:right;font-style:normal">
                        </spam>
                      </div>
                      <div style="margin:20px 20px">
                        <%= t.content %>
                      </div>
                    </p>
                  </div>  
                <% end %>
              <% end %>
            </div>
            <div style="text-align: center;background-color: green;height:10px"> </div>
          </p>
        </li>
      <% end %>
    <% end %>

  <h2 style="color:#2a638f;margin-left:30px"> <%= @question.answers.size %> Respuesta(s) </h2>
  <div>
    <% @question.answers.sort {|a,b| b.score <=> a.score }.each do |c| %>
      <% if c.fav != 1 %>
        <% if c.content %>
          <li style="list-style:none;border-top:1px solid #2a638f">
            <p>
              <div style="font-style:italic">
                <b>Autor:</b> <%= User.find(c.user_id).login %>
                <b> | Fecha: </b>
                <%= c.created_at.day %>/<%= c.created_at.month %>/<%= c.created_at.year %>
                <%= c.created_at.strftime("%I:%M%p") %>

                <spam style="float:right;font-style:normal">
                  <% if current_user == User.find(@question.user_id) %> 
                      <%= link_to '⭐', answers_favorite_path(:id => @question, :answer => c), :style => 'color:green' %>
                  <% end %>
                  <b>Score: </b><%= c.score %>
                  <%= link_to '⬆', answers_up_path(:id => @question, :answer => c), :style => 'color:green' %>          
                  <%= link_to '⬇', answers_down_path(:id => @question, :answer => c), :style => 'color:red' %>
                  <%= link_to 'Comentar', new_question_answer_comment_as_path(@question, c), :class => 'boton' %>
                </spam>
              </div>
              <div style="margin:20px 20px">
                <%= c.content %>
                <% c.comment_as.each do |t| %>
                  <% if t.content %>
                    <div style="font-size:small;margin-left:120px;border-top:5px double #999">
                      <p>
                        <div style="font-style:italic">
                          <b>Autor:</b> <%= User.find(t.user_id).login %>
                          <b> | Fecha: </b>
                          <%= t.created_at.day %>/<%= t.created_at.month %>/<%= t.created_at.year %>
                          <%= t.created_at.strftime("%I:%M%p") %>
                          <spam style="float:right;font-style:normal">
                          </spam>
                        </div>
                        <div style="margin:20px 20px">
                          <%= t.content %>
                        </div>
                      </p>
                    </div>  
                  <% end %>
                <% end %>
              </div>
            </p>
          </li>
        <% end %>
      <% end %>
    <% end %>

    <% if user_signed_in? && current_user.role =="user" %>
    <div style="padding-top:20px;border-top:4px dotted #2a638f;margin-left:20px;margin-right: 470px;">
      <spam style="margin-left:20px;font-style:italic"><b> Deja tu respuesta </b></spam>
      <%= form_for [@question, @question.answers.build] do |f| %>
        <div class="field">
          <%= f.text_area :content, :cols => 70, :rows => 5, :placeholder => "Responde la pregunta." %>
        </div>
        <div class="actions">
          <%= f.submit "Responder" %>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>