D-Answer/config/routes.rb
require 'role_model'
DAnswer::Application.routes.draw do  
  
  get "my_questions/index"

  get "questions/up"

  get "questions/down"

  get "answers/up"

  get "answers/down"

  get "answers/favorite"

  get "home/index"
  get 'tags/:tag', to: 'questions#index', as: :tag
  get 'tags/', to: 'tags#index'
  
  devise_for :users

  resources :users
  
  resources :questions do
    resources :comment_qs
    resources :answers do
      resource :comment_as 
    end
  end
    

  root :to => 'questions#index'

end

D-Answer/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == "admin"
        can [:read, :update, :destroy, :create], User#, Tutorial]
        can [:read, :destroy], [Question, CommentA, CommentQ, Answer]
        cannot :create, Answer
    elsif user.role == "user"
        can [:create, :read], [Question, Answer, CommentA, CommentQ]
        can :update, [User, Answer, CommentA, CommentQ]
        can :read, User
        can :destroy, Question
    end
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

D-Answer/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user, :class_name => "User", :foreign_key=>"user_id", :inverse_of => :answers
  
  has_many :voteanswers
  has_many :users, :through => :voteanswers

  belongs_to :question
  
  has_many :comment_as, :class_name => "CommentA", :inverse_of => :answer
  
  attr_accessible :answered_on, :content, :score, :fav
end

D-Answer/app/models/comment_a.rb
class CommentA < ActiveRecord::Base
  belongs_to :user, :class_name => "User", :foreign_key => "user_id", :inverse_of => :commentas
  
  belongs_to :answer, :class_name => "Answer", :foreign_key => "answer_id", :inverse_of => :comment_as
  
  attr_accessible :commented_on, :content

  VALID_STRING_REGEX = /\A[\w+\-\\!\?\,\.\"\' .]*\z/

#  validates :content, presence: true, uniqueness: true, format: { with: VALID_STRING_REGEX }
end

D-Answer/app/models/comment_q.rb
class CommentQ < ActiveRecord::Base
  belongs_to :user, :class_name => "User", :foreign_key => "user_id", :inverse_of => :commentqs
  
  belongs_to :question
  
  attr_accessible :commented_on, :content

  VALID_STRING_REGEX = /\A[\w+\-\\!\?\,\.\"\' .]*\z/

  # validates :content, presence: true, uniqueness: true, format: { with: VALID_STRING_REGEX }
end

D-Answer/app/models/question.rb
class Question < ActiveRecord::Base
  has_many :votequestions
  has_many :users, :through => :votequestions

  belongs_to :user
  
  has_many :answers, :dependent => :destroy
  
  has_many :comment_qs, :dependent => :destroy
  
  accepts_nested_attributes_for :comment_qs, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  attr_accessible :title, :category, :content, :published_on, :created_at, :score, :tag_list
  
  acts_as_taggable
  

  VALID_STRING_REGEX = /\A[\w+\-\\!\?\,\.\"\' .]*\z/

  validates :title, presence: true, uniqueness: true, format: { with: VALID_STRING_REGEX }
  validates :content, presence: true, format: { with: VALID_STRING_REGEX }
  
  def self.search(search)
    if search
      find(:all, :conditions => ['title LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

D-Answer/app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name
end

D-Answer/app/models/user.rb
require 'role_model'

class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :votequestions
  has_many :questions, :through => :votequestions

  has_many :voteanswers
  has_many :answers, :through => :voteanswers

  has_many :questions, :class_name => "Question"
  has_many :answers, :class_name => "Answer"
  has_many :commentqs, :class_name => "CommentQ"
  has_many :commentas, :class_name => "CommentA"
  
  has_attached_file :pic, :styles => { :small => "100x100>" },
                          :url  => "/assets/products/:id/:style/:basename.:extension",
                          :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"


  ROLES = %w[admin user]

  include RoleModel 
  roles :admin, :user
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :login, :name, :lastname, :bio, :rating, :role, :score, :pic
    
  # optionally set the integer attribute to store the roles in,
  # :roles_mask is the default
  roles_attribute :roles_mask
  
  #validates_numericality_of :rating
  VALID_STRING_REGEX = /\A[\w+\-\\!\?\,\.\"\' .]*\z/
  validates :login, presence: true, uniqueness: true, format: { with: VALID_STRING_REGEX }, :length => { :in => 1..15 }
  validates :name, format: { with: VALID_STRING_REGEX }
  validates :lastname, format: { with: VALID_STRING_REGEX }
  validates :password, format: { with: VALID_STRING_REGEX }
end

D-Answer/app/models/voteanswer.rb
class Voteanswer < ActiveRecord::Base
  belongs_to :user
  belongs_to :answer
  attr_accessible :answer_id, :user_id, :vote
end

D-Answer/app/models/votequestion.rb
class Votequestion < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  attr_accessible :question_id, :user_id, :vote
end

D-Answer/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      @questions = Question.all
      if user_signed_in?
        render :template => 'questions/index'
      end
  end
end

D-Answer/app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    render :nothing => true
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

D-Answer/app/helpers/answers_helper.rb
module AnswersHelper
end

D-Answer/app/helpers/application_helper.rb
module ApplicationHelper
  def devise_mapping
      Devise.mappings[:user]
  end

  def is_user?(user)
    usr_role = Role.find(:first, :conditions => ["name = ?", "User"])
    return user.roles.include?(usr_role)
  end

  def is_admin?(user)
    admin_role = Role.find(:first, :conditions => ["name = ?", "Admin"])
    return user.roles.include?(admin_role)
  end
  
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil), {:class => css_class}
  end
end

D-Answer/app/helpers/comment_qs_helper.rb
module CommentQsHelper
end

D-Answer/app/helpers/commenta_helper.rb
module CommentaHelper
end

D-Answer/app/helpers/home_helper.rb
module HomeHelper
end

D-Answer/app/helpers/my_questions_helper.rb
module MyQuestionsHelper
end

D-Answer/app/helpers/questions_helper.rb
module QuestionsHelper
end

D-Answer/app/helpers/tags_helper.rb
module TagsHelper
end

D-Answer/app/helpers/users_helper.rb
module UsersHelper
end

D-Answer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
    <script type="text/javascript"> 
      $(document).ready( function() {
        $('#deletesuccess').delay(5000).fadeOut();
      });
    </script>

    <title>D-Answer</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <header>
    <div id="head_title">
      <div style="font-size:xx-large;font-style:italic;font-weight:bold;float:left;margin-left:140px">
        D-Answer
      </div>
      <% if user_signed_in? %> 

        <div style="float:right;width:390px">
          <div style="padding-top:10px;float:left">
            Bienvenido, <%= current_user.login %>
          </div>
          <div style="margin-left:10px;margin-right:120px;margin-top:10px;float:right">
            <%= link_to "Perfil", current_user, :class => 'boton' %>
            <%= link_to 'Salir', destroy_user_session_path, :method => :delete, :class => 'boton'%>
          </div>
        </div>

      <% else %>
        <div style="padding-top:10px;float:right;width:575px">
          <div style="float:left">
            <%= link_to "Sign in", new_session_path(:user), :class => 'boton' %><br />
          </div>
          <div style="margin-right:120px;float:right"> No estás registrado? Regístrate y comienza a preguntar!
            <%= link_to "Sign up", new_registration_path(:user), :class => 'boton' %><br />
          </div>
        </div>  
      <% end %>
    </div>
    <ul id="head_menu">
      <% if not user_signed_in? %>
        <%= link_to content_tag(:li, 'Preguntas', :class => "nav"), questions_path %>
	      <%= link_to content_tag(:li, 'Tags', :class => "nav", :id => "last"), tags_path %>
      <% else %>
        <%= link_to content_tag(:li, 'Preguntas', :class => "nav"), questions_path %>
        <%= link_to content_tag(:li, 'Tags', :class => "nav"), tags_path %>
        <% if current_user.role == "admin" %>
          <%= link_to content_tag(:li, 'Listar Usuarios', :class => "nav", :id => "last"), users_path %>
        <% else %>
          <%= link_to content_tag(:li, 'Mis Preguntas', :class => "nav", :id => "last"), my_questions_index_path %>
	  
        <% end %>
    <% end %>
    </ul>
  </header>
  <body>
    <div id="wrapper">  
      <div id="deletesuccess" style="text-align:center;color:white;">
        <p class="notice" style="background:rgba(68,217,74,0.6);"><%= notice %></p>
        <p class="alert" style="background:rgba(233,126,23,0.4);"><%= alert %></p>
      </div>
      <%= yield %>
    </div>
  </body>
</html>